spring:
  output:
    ansi:
      enabled: always
  application:
    name: stock-service
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - shutdown
  endpoint:
    shutdown:
      enabled: on
